# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: InfoMapper
nav:
- Home: index.md
- Introduction: introduction/introduction.md
- Getting Started: getting-started/getting-started.md
- InfoMapper Features: features/features.md
- Resources: resources/resources.md
- Troubleshooting: troubleshooting/troubleshooting.md
- Appendix - Install and Config:
  - Overview: appendix-install/overview.md
  - app-config.json: appendix-install/app-config.md
- Appendix - Release Notes:
  - Release Notes: appendix-release-notes/release-notes.md
  - Version 0: appendix-release-notes/release-notes-0.md
# ------- configuration properties ---------------
# Alphabetize
# ------------------------------------------------
copyright:  Copyright Open Water Foundation
# ------------------------------------------------
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
# ------------------------------------------------
# Google Analytics
# - see:  https://squidfunk.github.io/mkdocs-material/getting-started/#google-analytics
google_analytics:
 - 'UA-135465513-1'
 - auto
# ------------------------------------------------
# Favicon is supposed to automatically be found:
# - in docs/img/favicon.ico
# - is a copy of docs/images/OWF-Logo-Favicon-32x32.ico
# - instead, with Material them, have a different approach (see "theme" below)
# ------------------------------------------------
# Don't enable the repo URL because irritating edit icons are shown when editing really isn't allowed
#repo_url:  https://github.com/OpenWaterFoundation/owf-app-info-mapper-ng-doc-user
# ------------------------------------------------
site_author:  Open Water Foundation
site_description:  Open Water Foundation InfoMapper
# ------------------------------------------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
  name: material
  favicon:  'images/favicon.ico'
# ------------------------------------------------
# The following controls how URLs are created
# - As of MkDocs 1.0 the default is true meaning URLs to a page ABC is ABC/ rather than something/ABC.html.
# - see:  https://www.mkdocs.org/user-guide/configuration/#use_directory_urls
# use_directory_urls: true
# ------------------------------------------------
